import type { Metadata } from "next";
import { Manrope, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${manrope.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-zinc-50 dark:bg-zinc-950 text-zinc-950 dark:text-zinc-50">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster 
            position="top-center" 
            toastOptions={{
              success: {
                style: {
                  background: '#dcfce7', // light green (green-100)
                  color: '#000000', // black text
                  border: '1px solid #bbf7d0', // green-200
                },
              },
              error: {
                style: {
                  background: '#fee2e2', // light red (red-100)
                  color: '#000000', // black text
                  border: '1px solid #fecaca', // red-200
                },
              },
              style: {
                background: 'var(--toast-bg)', 
                color: 'var(--toast-text)', 
                border: '1px solid var(--toast-border)',
              }
            }}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
